### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by summer-ning** [huturen/youdao-translator#5]
在windows上，win+T 快捷键冲突了，希望可以自己设置快捷键

**Comment by huturen** [comment]
直接在vscode设置快捷键面板里面搜索 extension.youdaoTranslate 

<img width="929" alt="image" src="https://user-images.githubusercontent.com/5173298/157575047-6f0e03d8-d482-40df-bf69-2358e3e6e200.png">

**Comment by huturen** [comment]
extension.youdaoTranslate
